/* Generado automaticamente desde las fotos del catalogo. Editable a mano. */
const ARTIST = {
    "nombre":  "Peter Pollak",
    "disciplina":  "Pintor",
    "ciudad":  "Temuco · Santiago, Chile",
    "anios":  "Obra 1971 — 2026",
    "bio":  "Pinto lo que veo y lo que recuerdo: el mar y los lagos del sur, la gente en sus faenas, el cuerpo del natural. Cada cuadro intenta detener la luz un instante antes de que se disuelva.",
    "retrato":  "assets/retrato.jpg",
    "email":  "hola@peterpollak.cl",
    "instagram":  "https://instagram.com/",
    "telefono":  "+56 9 7791 7211",
    "whatsapp":  "56977917211"
};
const TEMATICAS = [
    "Marina",
    "Paisaje",
    "Figura",
    "Costumbrista"
];
const TECNICAS = [
    "Óleo",
    "Dibujo",
    "Bosquejo",
    "Lápiz"
];
const CATEGORIAS = [
    {
        "slug":  "marinas",
        "nombre":  "Marinas",
        "descripcion":  "Botes, veleros y orillas: el mar y los lagos del sur como horizonte y memoria."
    },
    {
        "slug":  "paisajes",
        "nombre":  "Paisajes",
        "descripcion":  "De la cordillera y el altiplano a la Patagonia; ríos, bosques y volcanes."
    },
    {
        "slug":  "figura",
        "nombre":  "Figura y retrato",
        "descripcion":  "El cuerpo y el rostro pintados del natural: desnudos, musas y retratos."
    },
    {
        "slug":  "escenas",
        "nombre":  "Escenas y oficios",
        "descripcion":  "Huasos, pescadores, mercados y faenas: la vida de la gente y su trabajo."
    },
    {
        "slug":  "dibujos",
        "nombre":  "Dibujos",
        "descripcion":  "Apuntes a lápiz del natural, muchos de ellos base de óleos posteriores."
    }
];
const OBRAS = [
    {
        "id":  "1001-desnudo",
        "titulo":  "Desnudo",
        "anio":  1971,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1001-desnudo.jpg",
        "destacada":  false
    },
    {
        "id":  "1002-hombre",
        "titulo":  "Hombre",
        "anio":  1971,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1002-hombre.jpg",
        "destacada":  false
    },
    {
        "id":  "1003-mujer",
        "titulo":  "Mujer",
        "anio":  1971,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1003-mujer.jpg",
        "destacada":  false
    },
    {
        "id":  "1004-bote-en-playa",
        "titulo":  "Bote en playa",
        "anio":  1972,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1004-bote-en-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1005-camino-agreste",
        "titulo":  "Camino agreste",
        "anio":  1972,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1005-camino-agreste.jpg",
        "destacada":  false
    },
    {
        "id":  "1006-huaso",
        "titulo":  "Huaso",
        "anio":  null,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1006-huaso.jpg",
        "destacada":  false
    },
    {
        "id":  "1007-machi",
        "titulo":  "Machi",
        "anio":  1974,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1007-machi.jpg",
        "destacada":  false
    },
    {
        "id":  "1008-botes-en-la-playa",
        "titulo":  "Botes en la playa",
        "anio":  1974,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1008-botes-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1009-puertecito",
        "titulo":  "Puertecito",
        "anio":  1975,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1009-puertecito.jpg",
        "destacada":  false
    },
    {
        "id":  "1010-puertecito",
        "titulo":  "Puertecito",
        "anio":  1975,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1010-puertecito.jpg",
        "destacada":  false
    },
    {
        "id":  "1011-puertecito1975",
        "titulo":  "Puertecito1975",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1011-puertecito1975.jpg",
        "destacada":  false
    },
    {
        "id":  "1012-hombre-sentado",
        "titulo":  "Hombre sentado",
        "anio":  1975,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1012-hombre-sentado.jpg",
        "destacada":  false
    },
    {
        "id":  "1013-caribe",
        "titulo":  "Caribe",
        "anio":  1975,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1013-caribe.jpg",
        "destacada":  false
    },
    {
        "id":  "1014-sanantonio",
        "titulo":  "SanAntonio",
        "anio":  1998,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1014-sanantonio.jpg",
        "destacada":  false
    },
    {
        "id":  "1015-musa",
        "titulo":  "Musa",
        "anio":  1998,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1015-musa.jpg",
        "destacada":  false
    },
    {
        "id":  "1015-placidez",
        "titulo":  "Placidez",
        "anio":  1998,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1015-placidez.jpg",
        "destacada":  false
    },
    {
        "id":  "1016-musa",
        "titulo":  "Musa",
        "anio":  1999,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1016-musa.jpg",
        "destacada":  false
    },
    {
        "id":  "1017-mujer-tendida-en-playa",
        "titulo":  "Mujer tendida en playa",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1017-mujer-tendida-en-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1018-dibujo2002",
        "titulo":  "Dibujo2002",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Dibujo",
        "medidas":  "",
        "imagen":  "assets/obras/1018-dibujo2002.jpg",
        "destacada":  false
    },
    {
        "id":  "1018-mujer-tendida-2-dibujo-original",
        "titulo":  "Mujer tendida 2 dibujo original",
        "anio":  2002,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Dibujo",
        "medidas":  "",
        "imagen":  "assets/obras/1018-mujer-tendida-2-dibujo-original.jpg",
        "destacada":  false
    },
    {
        "id":  "1019-mujer-tendida-bosquejo-a-color",
        "titulo":  "Mujer tendida bosquejo a color",
        "anio":  2022,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Bosquejo",
        "medidas":  "",
        "imagen":  "assets/obras/1019-mujer-tendida-bosquejo-a-color.jpg",
        "destacada":  false
    },
    {
        "id":  "1020-mujer-sentada-dibujo-original",
        "titulo":  "Mujer sentada dibujo original",
        "anio":  2002,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Dibujo",
        "medidas":  "",
        "imagen":  "assets/obras/1020-mujer-sentada-dibujo-original.jpg",
        "destacada":  false
    },
    {
        "id":  "1021-mujer-sentada-bosquejo-a-color",
        "titulo":  "Mujer sentada bosquejo a color",
        "anio":  2022,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Bosquejo",
        "medidas":  "",
        "imagen":  "assets/obras/1021-mujer-sentada-bosquejo-a-color.jpg",
        "destacada":  false
    },
    {
        "id":  "1022-barcos-caribe",
        "titulo":  "Barcos Caribe",
        "anio":  2022,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1022-barcos-caribe.jpg",
        "destacada":  false
    },
    {
        "id":  "1025-mujer-tendida-sobre-cama",
        "titulo":  "Mujer tendida sobre cama",
        "anio":  2022,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1025-mujer-tendida-sobre-cama.jpg",
        "destacada":  false
    },
    {
        "id":  "1025-mujer-tomando-sol",
        "titulo":  "Mujer tomando sol",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1025-mujer-tomando-sol.jpg",
        "destacada":  false
    },
    {
        "id":  "1026-costa-valdivia",
        "titulo":  "Costa Valdivia",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1026-costa-valdivia.jpg",
        "destacada":  false
    },
    {
        "id":  "1027-caburgua-2",
        "titulo":  "Caburgua 2",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1027-caburgua-2.jpg",
        "destacada":  false
    },
    {
        "id":  "1028-sl-e-foster",
        "titulo":  "SL E Foster",
        "anio":  2023,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1028-sl-e-foster.jpg",
        "destacada":  false
    },
    {
        "id":  "1029-botes-en-playa",
        "titulo":  "Botes en playa",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1029-botes-en-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1030-obras-publicas-5-1",
        "titulo":  "Obras Publicas 5-1",
        "anio":  2024,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1030-obras-publicas-5-1.jpg",
        "destacada":  false
    },
    {
        "id":  "1030-pescadores-en-el-rio",
        "titulo":  "Pescadores en el rio",
        "anio":  2023,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1030-pescadores-en-el-rio.jpg",
        "destacada":  false
    },
    {
        "id":  "1031-caburgua",
        "titulo":  "Caburgua",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1031-caburgua.jpg",
        "destacada":  false
    },
    {
        "id":  "1032-pescadores-rio-tolten",
        "titulo":  "Pescadores rio Tolten",
        "anio":  2023,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1032-pescadores-rio-tolten.jpg",
        "destacada":  false
    },
    {
        "id":  "1033-zapallar",
        "titulo":  "Zapallar",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1033-zapallar.jpg",
        "destacada":  false
    },
    {
        "id":  "1034-sofia-caburgua-2",
        "titulo":  "Sofia Caburgua 2",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1034-sofia-caburgua-2.jpg",
        "destacada":  false
    },
    {
        "id":  "1035-sofia-caburgua",
        "titulo":  "Sofia Caburgua",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1035-sofia-caburgua.jpg",
        "destacada":  false
    },
    {
        "id":  "1036-bote-en-caburgua",
        "titulo":  "Bote en Caburgua",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1036-bote-en-caburgua.jpg",
        "destacada":  false
    },
    {
        "id":  "1037-rio-cruces",
        "titulo":  "Rio cruces",
        "anio":  2023,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1037-rio-cruces.jpg",
        "destacada":  false
    },
    {
        "id":  "1038-veleros-cielo-gris",
        "titulo":  "Veleros cielo gris",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1038-veleros-cielo-gris.jpg",
        "destacada":  false
    },
    {
        "id":  "1039-veleros-cielo-anaranjado",
        "titulo":  "Veleros cielo anaranjado",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1039-veleros-cielo-anaranjado.jpg",
        "destacada":  false
    },
    {
        "id":  "1040-veleros-varados",
        "titulo":  "Veleros varados",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1040-veleros-varados.jpg",
        "destacada":  false
    },
    {
        "id":  "1041-bote-antiguo-caburgua",
        "titulo":  "Bote antiguo caburgua",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1041-bote-antiguo-caburgua.jpg",
        "destacada":  false
    },
    {
        "id":  "1041-mujer-en-la-playa",
        "titulo":  "Mujer en la playa",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1041-mujer-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1042-veleros-vela-roja",
        "titulo":  "Veleros vela roja",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1042-veleros-vela-roja.jpg",
        "destacada":  false
    },
    {
        "id":  "1043-bote-caburgua",
        "titulo":  "Bote caburgua",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1043-bote-caburgua.jpg",
        "destacada":  false
    },
    {
        "id":  "1044-velero-vela-azul",
        "titulo":  "Velero vela azul",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1044-velero-vela-azul.jpg",
        "destacada":  false
    },
    {
        "id":  "1045-velero-jamaica",
        "titulo":  "Velero Jamaica",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1045-velero-jamaica.jpg",
        "destacada":  false
    },
    {
        "id":  "1046-velero-fondo-aamarillo",
        "titulo":  "Velero fondo aamarillo",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1046-velero-fondo-aamarillo.jpg",
        "destacada":  false
    },
    {
        "id":  "1047-veleros-oriente",
        "titulo":  "Veleros Oriente",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1047-veleros-oriente.jpg",
        "destacada":  false
    },
    {
        "id":  "1049-playa",
        "titulo":  "Playa",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1049-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1050-playa-con-velero",
        "titulo":  "Playa con velero",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1050-playa-con-velero.jpg",
        "destacada":  false
    },
    {
        "id":  "1050-1-pescadores-en-playa",
        "titulo":  "Pescadores en playa",
        "anio":  2023,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1050-1-pescadores-en-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1051-cruzando-el-salar-de-uyuni",
        "titulo":  "Cruzando el salar de Uyuni",
        "anio":  2023,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1051-cruzando-el-salar-de-uyuni.jpg",
        "destacada":  false
    },
    {
        "id":  "1052-entrada-a-valle-de-la-luna-san-pedro",
        "titulo":  "Entrada a valle de la luna san Pedro",
        "anio":  2023,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1052-entrada-a-valle-de-la-luna-san-pedro.jpg",
        "destacada":  false
    },
    {
        "id":  "1053-calle-de-san-perdo-de-atacama",
        "titulo":  "Calle de San Perdo de Atacama",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1053-calle-de-san-perdo-de-atacama.jpg",
        "destacada":  false
    },
    {
        "id":  "1054-casa-flotante-con-botes",
        "titulo":  "Casa flotante con botes",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1054-casa-flotante-con-botes.jpg",
        "destacada":  false
    },
    {
        "id":  "1055-altiplano-en-moto",
        "titulo":  "Altiplano en moto",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1055-altiplano-en-moto.jpg",
        "destacada":  false
    },
    {
        "id":  "1056-salar-uyuni-isla-incahuasi",
        "titulo":  "Salar uyuni isla Incahuasi",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1056-salar-uyuni-isla-incahuasi.jpg",
        "destacada":  false
    },
    {
        "id":  "1057-desbudo-sobre-cama-dibujo-original",
        "titulo":  "Desbudo sobre cama dibujo original",
        "anio":  2002,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Dibujo",
        "medidas":  "",
        "imagen":  "assets/obras/1057-desbudo-sobre-cama-dibujo-original.jpg",
        "destacada":  false
    },
    {
        "id":  "1058-desnudo-sobre-cama",
        "titulo":  "Desnudo sobre cama",
        "anio":  2023,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1058-desnudo-sobre-cama.jpg",
        "destacada":  false
    },
    {
        "id":  "1059-mujer-con-cartera",
        "titulo":  "Mujer con cartera",
        "anio":  2023,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1059-mujer-con-cartera.jpg",
        "destacada":  false
    },
    {
        "id":  "1060-caribe",
        "titulo":  "Caribe",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1060-caribe.jpg",
        "destacada":  false
    },
    {
        "id":  "1061-chaise-longe-au-lac",
        "titulo":  "Chaise longe au lac",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1061-chaise-longe-au-lac.jpg",
        "destacada":  false
    },
    {
        "id":  "1062-valle-de-la-luna-atacama",
        "titulo":  "Valle de la Luna Atacama",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1062-valle-de-la-luna-atacama.jpg",
        "destacada":  false
    },
    {
        "id":  "1063-mercado",
        "titulo":  "Mercado",
        "anio":  null,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1063-mercado.jpg",
        "destacada":  false
    },
    {
        "id":  "1064-mujer-desnuda-3-dibujo-original",
        "titulo":  "Mujer desnuda 3 dibujo original",
        "anio":  2002,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Dibujo",
        "medidas":  "",
        "imagen":  "assets/obras/1064-mujer-desnuda-3-dibujo-original.jpg",
        "destacada":  false
    },
    {
        "id":  "1065-mujer-desnuda",
        "titulo":  "Mujer desnuda",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1065-mujer-desnuda.jpg",
        "destacada":  false
    },
    {
        "id":  "1066-velero-perdido-en-lago",
        "titulo":  "Velero perdido en lago",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1066-velero-perdido-en-lago.jpg",
        "destacada":  false
    },
    {
        "id":  "1067-mujeres-en-playa",
        "titulo":  "Mujeres en playa",
        "anio":  2023,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1067-mujeres-en-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1068-playa-n-jamaica-corregida",
        "titulo":  "Playa N Jamaica corregida",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1068-playa-n-jamaica-corregida.jpg",
        "destacada":  false
    },
    {
        "id":  "1069-caburgua-con-ninos",
        "titulo":  "Caburgua con ninos",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1069-caburgua-con-ninos.jpg",
        "destacada":  false
    },
    {
        "id":  "1070-puesta-de-sol-en-puertecito",
        "titulo":  "Puesta de sol en Puertecito",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1070-puesta-de-sol-en-puertecito.jpg",
        "destacada":  false
    },
    {
        "id":  "1071-nino-en-playa-bajo-sompra",
        "titulo":  "Nino en playa bajo sompra",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1071-nino-en-playa-bajo-sompra.jpg",
        "destacada":  false
    },
    {
        "id":  "1072-nino-jugando-en-el-agua",
        "titulo":  "Nino jugando en el agua",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1072-nino-jugando-en-el-agua.jpg",
        "destacada":  false
    },
    {
        "id":  "1073-alimentndo-los-peces-en-cultivo-salmones-estero-tocoihue",
        "titulo":  "Alimentndo los peces en Cultivo Salmones Estero Tocoihue",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1073-alimentndo-los-peces-en-cultivo-salmones-estero-tocoihue.jpg",
        "destacada":  false
    },
    {
        "id":  "1074-playa-caribe-con-muelle",
        "titulo":  "Playa Caribe con muelle",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1074-playa-caribe-con-muelle.jpg",
        "destacada":  false
    },
    {
        "id":  "1075-ensenada-lago-caburgua",
        "titulo":  "Ensenada Lago Caburgua",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1075-ensenada-lago-caburgua.jpg",
        "destacada":  false
    },
    {
        "id":  "1076-mujer-de-espalda-en-la-playa",
        "titulo":  "Mujer de espalda en la playa",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1076-mujer-de-espalda-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1077-angelmo",
        "titulo":  "Angelmo",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1077-angelmo.jpg",
        "destacada":  false
    },
    {
        "id":  "1078-renahue-caburgua-playa-con-botes",
        "titulo":  "Renahue Caburgua playa con botes",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1078-renahue-caburgua-playa-con-botes.jpg",
        "destacada":  false
    },
    {
        "id":  "1079-marea-baja-en-pargua",
        "titulo":  "Marea Baja en Pargua",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1079-marea-baja-en-pargua.jpg",
        "destacada":  false
    },
    {
        "id":  "1080-puesta-de-sol-en-puertecillo",
        "titulo":  "Puesta de sol en puertecillo",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1080-puesta-de-sol-en-puertecillo.jpg",
        "destacada":  false
    },
    {
        "id":  "1081-plantas-acuaticas",
        "titulo":  "Plantas acuaticas",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1081-plantas-acuaticas.jpg",
        "destacada":  false
    },
    {
        "id":  "1082-bote-en-playa-caburgua",
        "titulo":  "Bote en playa Caburgua",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1082-bote-en-playa-caburgua.jpg",
        "destacada":  false
    },
    {
        "id":  "1083-desembocaduras-estero-renahue",
        "titulo":  "Desembocaduras estero Renahue",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1083-desembocaduras-estero-renahue.jpg",
        "destacada":  false
    },
    {
        "id":  "1084-retrato-mujer",
        "titulo":  "Retrato mujer",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1084-retrato-mujer.jpg",
        "destacada":  false
    },
    {
        "id":  "1085-lago-caburgua-playa-renahue",
        "titulo":  "Lago Caburgua,playa Renahue",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1085-lago-caburgua-playa-renahue.jpg",
        "destacada":  false
    },
    {
        "id":  "1086-saltos-del-petrohue",
        "titulo":  "Saltos del Petrohue",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1086-saltos-del-petrohue.jpg",
        "destacada":  false
    },
    {
        "id":  "1087-plantas-en-el-agua",
        "titulo":  "Plantas en el agua",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1087-plantas-en-el-agua.jpg",
        "destacada":  false
    },
    {
        "id":  "1088-retrato-de-mujer",
        "titulo":  "Retrato de mujer",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1088-retrato-de-mujer.jpg",
        "destacada":  false
    },
    {
        "id":  "1089-familiaa-en-la-playa",
        "titulo":  "Familiaa en la playa",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1089-familiaa-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1090-retrato-xs",
        "titulo":  "Retrato XS",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1090-retrato-xs.jpg",
        "destacada":  false
    },
    {
        "id":  "1091-rio-puelo",
        "titulo":  "Rio Puelo",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1091-rio-puelo.jpg",
        "destacada":  false
    },
    {
        "id":  "1092-la-asistente-de-vuelo",
        "titulo":  "La asistente de vuelo",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1092-la-asistente-de-vuelo.jpg",
        "destacada":  false
    },
    {
        "id":  "1093-botes-en-calbuco-con-marea-baja",
        "titulo":  "Botes en Calbuco con marea baja",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1093-botes-en-calbuco-con-marea-baja.jpg",
        "destacada":  false
    },
    {
        "id":  "1094-puerto-plata-rd",
        "titulo":  "Puerto Plata RD",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1094-puerto-plata-rd.jpg",
        "destacada":  false
    },
    {
        "id":  "1095-playa-sosua-2-rd",
        "titulo":  "Playa Sosua 2 RD",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1095-playa-sosua-2-rd.jpg",
        "destacada":  false
    },
    {
        "id":  "1096-escena-playa",
        "titulo":  "Escena playa",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1096-escena-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1097-asistente-vuelo-copa",
        "titulo":  "Asistente vuelo copa",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1097-asistente-vuelo-copa.jpg",
        "destacada":  false
    },
    {
        "id":  "1097-asistente-vuelo-copa-2",
        "titulo":  "Asistente Vuelo Copa",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1097-asistente-vuelo-copa-2.jpg",
        "destacada":  false
    },
    {
        "id":  "1098-playa-sousa-rd",
        "titulo":  "Playa Sousa RD",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1098-playa-sousa-rd.jpg",
        "destacada":  false
    },
    {
        "id":  "1099-velero-an-alta-mar-sousa-rd",
        "titulo":  "Velero an alta mar Sousa RD",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1099-velero-an-alta-mar-sousa-rd.jpg",
        "destacada":  false
    },
    {
        "id":  "1100-mercado-santiago-de-los-caballeros",
        "titulo":  "Mercado Santiago de los Caballeros",
        "anio":  null,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1100-mercado-santiago-de-los-caballeros.jpg",
        "destacada":  false
    },
    {
        "id":  "1101-mercado-santiago-de-los-caballeros",
        "titulo":  "Mercado Santiago de los Caballeros",
        "anio":  null,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1101-mercado-santiago-de-los-caballeros.jpg",
        "destacada":  false
    },
    {
        "id":  "1102-escena-campo-y-rio",
        "titulo":  "Escena campo y rio",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1102-escena-campo-y-rio.jpg",
        "destacada":  false
    },
    {
        "id":  "1103-bote-con-pescadores-sosua-rd",
        "titulo":  "Bote con pescadores Sosua RD",
        "anio":  2024,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1103-bote-con-pescadores-sosua-rd.jpg",
        "destacada":  false
    },
    {
        "id":  "1104-mujer-en-el-mar",
        "titulo":  "Mujer en el mar",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1104-mujer-en-el-mar.jpg",
        "destacada":  false
    },
    {
        "id":  "1106-mujer-neanderthal",
        "titulo":  "Mujer Neanderthal",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1106-mujer-neanderthal.jpg",
        "destacada":  false
    },
    {
        "id":  "1107-playa-sur-sosua",
        "titulo":  "Playa sur Sosua",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1107-playa-sur-sosua.jpg",
        "destacada":  false
    },
    {
        "id":  "1108-asistente-vuelo-copa",
        "titulo":  "Asistente vuelo Copa",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1108-asistente-vuelo-copa.jpg",
        "destacada":  false
    },
    {
        "id":  "1109-bahia-fishguard-uk",
        "titulo":  "Bahia Fishguard UK",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1109-bahia-fishguard-uk.jpg",
        "destacada":  false
    },
    {
        "id":  "1110-camarera-restaurant-rd",
        "titulo":  "Camarera restaurant RD",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1110-camarera-restaurant-rd.jpg",
        "destacada":  false
    },
    {
        "id":  "1111-neanderthal-madre",
        "titulo":  "Neanderthal madre",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1111-neanderthal-madre.jpg",
        "destacada":  false
    },
    {
        "id":  "1112-hombre-hablando-por-celular",
        "titulo":  "Hombre hablando por celular",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1112-hombre-hablando-por-celular.jpg",
        "destacada":  false
    },
    {
        "id":  "1113-botes-en-calbuco",
        "titulo":  "Botes en Calbuco",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1113-botes-en-calbuco.jpg",
        "destacada":  false
    },
    {
        "id":  "1114-muelle-con-aves-en-calbuco",
        "titulo":  "Muelle con aves en Calbuco",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1114-muelle-con-aves-en-calbuco.jpg",
        "destacada":  false
    },
    {
        "id":  "1115-retrato-sl",
        "titulo":  "Retrato SL",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1115-retrato-sl.jpg",
        "destacada":  false
    },
    {
        "id":  "1116-retrato-pb",
        "titulo":  "Retrato PB",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1116-retrato-pb.jpg",
        "destacada":  false
    },
    {
        "id":  "1117-desnuda-en-la-playa",
        "titulo":  "Desnuda en la playa",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1117-desnuda-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1118-mellizas-tendidas",
        "titulo":  "Mellizas tendidas",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1118-mellizas-tendidas.jpg",
        "destacada":  false
    },
    {
        "id":  "1119-noche-de-tormenta-en-el-lago",
        "titulo":  "Noche de tormenta en el lago",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1119-noche-de-tormenta-en-el-lago.jpg",
        "destacada":  false
    },
    {
        "id":  "1120-en-calbuco",
        "titulo":  "En Calbuco",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1120-en-calbuco.jpg",
        "destacada":  false
    },
    {
        "id":  "1121-mujer-con-abrigo",
        "titulo":  "Mujer con abrigo",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1121-mujer-con-abrigo.jpg",
        "destacada":  false
    },
    {
        "id":  "1122-mujer-con-bufanda",
        "titulo":  "Mujer con bufanda",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1122-mujer-con-bufanda.jpg",
        "destacada":  false
    },
    {
        "id":  "1123-torso-de-mujer-desnuda",
        "titulo":  "Torso de mujer desnuda",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1123-torso-de-mujer-desnuda.jpg",
        "destacada":  false
    },
    {
        "id":  "1124-lago-en-noche-oscura",
        "titulo":  "Lago en noche oscura",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1124-lago-en-noche-oscura.jpg",
        "destacada":  false
    },
    {
        "id":  "1125-mi-taller-de-verano",
        "titulo":  "Mi taller de verano",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1125-mi-taller-de-verano.jpg",
        "destacada":  false
    },
    {
        "id":  "1126-mujer-en-traje-con-velo",
        "titulo":  "Mujer en traje con velo",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1126-mujer-en-traje-con-velo.jpg",
        "destacada":  false
    },
    {
        "id":  "1127-retrato-mujer-rubia",
        "titulo":  "Retrato mujer rubia",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1127-retrato-mujer-rubia.jpg",
        "destacada":  false
    },
    {
        "id":  "1128-obras-publica-4-1",
        "titulo":  "Obras Publica 4-1",
        "anio":  2024,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1128-obras-publica-4-1.jpg",
        "destacada":  false
    },
    {
        "id":  "1129-mujer-con-vaso",
        "titulo":  "Mujer con vaso",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1129-mujer-con-vaso.jpg",
        "destacada":  false
    },
    {
        "id":  "1131-un-comienzo-realjado",
        "titulo":  "Un comienzo realjado",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1131-un-comienzo-realjado.jpg",
        "destacada":  false
    },
    {
        "id":  "1132-observando-el-horizonte",
        "titulo":  "Observando el horizonte",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1132-observando-el-horizonte.jpg",
        "destacada":  false
    },
    {
        "id":  "1133-arbol-quemado-en-el-lago",
        "titulo":  "Arbol quemado en el lago",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1133-arbol-quemado-en-el-lago.jpg",
        "destacada":  false
    },
    {
        "id":  "1134-rio-de-lava-volcanica",
        "titulo":  "Rio de lava volcanica",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1134-rio-de-lava-volcanica.jpg",
        "destacada":  false
    },
    {
        "id":  "1135-decorando-la-casa",
        "titulo":  "Decorando la casa",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1135-decorando-la-casa.jpg",
        "destacada":  false
    },
    {
        "id":  "1136-retrato-ag",
        "titulo":  "Retrato AG",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1136-retrato-ag.jpg",
        "destacada":  false
    },
    {
        "id":  "1137-pescador",
        "titulo":  "Pescador",
        "anio":  null,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1137-pescador.jpg",
        "destacada":  false
    },
    {
        "id":  "1139-navegando-frente-al-faro",
        "titulo":  "Navegando frente al faro",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1139-navegando-frente-al-faro.jpg",
        "destacada":  false
    },
    {
        "id":  "1140-de-mar",
        "titulo":  "De mar",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1140-de-mar.jpg",
        "destacada":  false
    },
    {
        "id":  "1142-un-lago-en-el-volcan",
        "titulo":  "Un lago en el volcan",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1142-un-lago-en-el-volcan.jpg",
        "destacada":  false
    },
    {
        "id":  "1143-muelle-con-velero",
        "titulo":  "Muelle con velero",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1143-muelle-con-velero.jpg",
        "destacada":  false
    },
    {
        "id":  "1144-muelle-con-aves",
        "titulo":  "Muelle con aves",
        "anio":  2024,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1144-muelle-con-aves.jpg",
        "destacada":  false
    },
    {
        "id":  "1145-mujer-en-cuclillas",
        "titulo":  "Mujer en cuclillas",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1145-mujer-en-cuclillas.jpg",
        "destacada":  false
    },
    {
        "id":  "1146-puesta-de-sol",
        "titulo":  "Puesta de sol",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1146-puesta-de-sol.jpg",
        "destacada":  false
    },
    {
        "id":  "1147-riachuelo-entre-rocas",
        "titulo":  "Riachuelo entre rocas",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1147-riachuelo-entre-rocas.jpg",
        "destacada":  false
    },
    {
        "id":  "1148-el-bano-de-las-ninfas",
        "titulo":  "El Baño de las Ninfas",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1148-el-bano-de-las-ninfas.jpg",
        "destacada":  false
    },
    {
        "id":  "1149-tercera-edad-caminando-al-horizonte",
        "titulo":  "Tercera edad caminando al horizonte",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1149-tercera-edad-caminando-al-horizonte.jpg",
        "destacada":  false
    },
    {
        "id":  "1150-sol-de-la-manana",
        "titulo":  "Sol de la mañana",
        "anio":  2024,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1150-sol-de-la-manana.jpg",
        "destacada":  false
    },
    {
        "id":  "1151-torzo-en-las-sombras",
        "titulo":  "Torzo en las sombras",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1151-torzo-en-las-sombras.jpg",
        "destacada":  false
    },
    {
        "id":  "1152-sefora-buscando-la-pose",
        "titulo":  "Sefora buscando la pose",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1152-sefora-buscando-la-pose.jpg",
        "destacada":  false
    },
    {
        "id":  "1153-rio-en-las-montanas",
        "titulo":  "Rio en las montañas",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1153-rio-en-las-montanas.jpg",
        "destacada":  false
    },
    {
        "id":  "1154-obra-1154",
        "titulo":  "Obra 1154",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1154-obra-1154.jpg",
        "destacada":  false
    },
    {
        "id":  "1155-inversos",
        "titulo":  "Inversos",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1155-inversos.jpg",
        "destacada":  false
    },
    {
        "id":  "1156-fin-del-mundo-en-el-artico",
        "titulo":  "Fin del mundo en el artico",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1156-fin-del-mundo-en-el-artico.jpg",
        "destacada":  false
    },
    {
        "id":  "1157-las-bailarinas",
        "titulo":  "Las Bailarinas",
        "anio":  2025,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1157-las-bailarinas.jpg",
        "destacada":  false
    },
    {
        "id":  "1158-a-fire",
        "titulo":  "A Fire",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1158-a-fire.jpg",
        "destacada":  false
    },
    {
        "id":  "1159-la-cerca",
        "titulo":  "La cerca",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1159-la-cerca.jpg",
        "destacada":  false
    },
    {
        "id":  "1160-en-la-selva",
        "titulo":  "En la selva",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1160-en-la-selva.jpg",
        "destacada":  false
    },
    {
        "id":  "1161-lago-de-los-cisnes",
        "titulo":  "Lago de los Cisnes",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1161-lago-de-los-cisnes.jpg",
        "destacada":  false
    },
    {
        "id":  "1162-el-espejo-del-deseo",
        "titulo":  "EL espejo del deseo",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1162-el-espejo-del-deseo.jpg",
        "destacada":  false
    },
    {
        "id":  "1163-la-garza-perdida-en-la-playa",
        "titulo":  "La Garza perdida en la playa",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1163-la-garza-perdida-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1164-l-a-fire",
        "titulo":  "L A Fire",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1164-l-a-fire.jpg",
        "destacada":  false
    },
    {
        "id":  "1165-l-a-fires",
        "titulo":  "L A Fires",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1165-l-a-fires.jpg",
        "destacada":  false
    },
    {
        "id":  "1166-l-a-fires",
        "titulo":  "L A Fires",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1166-l-a-fires.jpg",
        "destacada":  false
    },
    {
        "id":  "1167-esquila-en-la-patagonia",
        "titulo":  "Esquila en la Patagonia",
        "anio":  2025,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1167-esquila-en-la-patagonia.jpg",
        "destacada":  false
    },
    {
        "id":  "1168-torso-de-mujer",
        "titulo":  "Torso de mujer",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1168-torso-de-mujer.jpg",
        "destacada":  false
    },
    {
        "id":  "1169-la-minga",
        "titulo":  "La Minga",
        "anio":  2025,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1169-la-minga.jpg",
        "destacada":  false
    },
    {
        "id":  "1170-bailarina",
        "titulo":  "Bailarina",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1170-bailarina.jpg",
        "destacada":  false
    },
    {
        "id":  "1172-desnudo-en-sofa",
        "titulo":  "Desnudo en sofa",
        "anio":  2025,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1172-desnudo-en-sofa.jpg",
        "destacada":  false
    },
    {
        "id":  "1173-la-cosecha",
        "titulo":  "La cosecha",
        "anio":  2025,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1173-la-cosecha.jpg",
        "destacada":  false
    },
    {
        "id":  "1174-arboles-en-el-lago",
        "titulo":  "Arboles en el lago",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1174-arboles-en-el-lago.jpg",
        "destacada":  false
    },
    {
        "id":  "1175-arboles-en-el-lago",
        "titulo":  "Arboles en el lago",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1175-arboles-en-el-lago.jpg",
        "destacada":  false
    },
    {
        "id":  "1176-tornero",
        "titulo":  "Tornero",
        "anio":  2025,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1176-tornero.jpg",
        "destacada":  true
    },
    {
        "id":  "1177-e-la-penumbra",
        "titulo":  "E la penumbra",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1177-e-la-penumbra.jpg",
        "destacada":  false
    },
    {
        "id":  "1178-el-maquinista",
        "titulo":  "EL Maquinista",
        "anio":  2025,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1178-el-maquinista.jpg",
        "destacada":  false
    },
    {
        "id":  "1179-pesca-industrial",
        "titulo":  "Pesca Industrial",
        "anio":  2025,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1179-pesca-industrial.jpg",
        "destacada":  true
    },
    {
        "id":  "1180-artesanal",
        "titulo":  "Artesanal",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1180-artesanal.jpg",
        "destacada":  false
    },
    {
        "id":  "1181-calle-de-santiago-del-1900",
        "titulo":  "Calle de Santiago del 1900",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1181-calle-de-santiago-del-1900.jpg",
        "destacada":  false
    },
    {
        "id":  "1182-riachuelo-entre-rocas",
        "titulo":  "Riachuelo entre rocas",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1182-riachuelo-entre-rocas.jpg",
        "destacada":  false
    },
    {
        "id":  "1183-bosquejo-sobrecargo-avion",
        "titulo":  "Bosquejo sobrecargo avion",
        "anio":  2024,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Bosquejo",
        "medidas":  "",
        "imagen":  "assets/obras/1183-bosquejo-sobrecargo-avion.jpg",
        "destacada":  false
    },
    {
        "id":  "1184-veleros-en-la-playa",
        "titulo":  "Veleros en la playa",
        "anio":  2023,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1184-veleros-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1185-patagonia-virgen",
        "titulo":  "Patagonia virgen",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1185-patagonia-virgen.jpg",
        "destacada":  false
    },
    {
        "id":  "1186-oscuro-tras-el-rio",
        "titulo":  "Oscuro tras el rio",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1186-oscuro-tras-el-rio.jpg",
        "destacada":  false
    },
    {
        "id":  "1187-osechando-la-uva",
        "titulo":  "Osechando la Uva",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1187-osechando-la-uva.jpg",
        "destacada":  false
    },
    {
        "id":  "1188-casas-de-piedra-abandonadas",
        "titulo":  "Casas de piedra abandonadas",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1188-casas-de-piedra-abandonadas.jpg",
        "destacada":  false
    },
    {
        "id":  "1189-muelle-en-el-lago",
        "titulo":  "Muelle en el lago",
        "anio":  2025,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1189-muelle-en-el-lago.jpg",
        "destacada":  true
    },
    {
        "id":  "1190-lago-con-neblina",
        "titulo":  "Lago con neblina",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1190-lago-con-neblina.jpg",
        "destacada":  false
    },
    {
        "id":  "1191-pueblo-frente-al-mar",
        "titulo":  "Pueblo frente al mar",
        "anio":  2025,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1191-pueblo-frente-al-mar.jpg",
        "destacada":  true
    },
    {
        "id":  "1192-puesta-de-sol-en-chicureo",
        "titulo":  "Puesta de sol en Chicureo",
        "anio":  2025,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1192-puesta-de-sol-en-chicureo.jpg",
        "destacada":  false
    },
    {
        "id":  "1193-pescadores-en-la-playa",
        "titulo":  "Pescadores en la playa",
        "anio":  null,
        "categoria":  "escenas",
        "tematica":  "Costumbrista",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1193-pescadores-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1194-paseo-por-le-playa",
        "titulo":  "Paseo por le playa",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1194-paseo-por-le-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1195-casas-blancas-frente-a-mar",
        "titulo":  "Casas Blancas frente a mar",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1195-casas-blancas-frente-a-mar.jpg",
        "destacada":  false
    },
    {
        "id":  "1196-torres-del-paine",
        "titulo":  "Torres del Paine",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1196-torres-del-paine.jpg",
        "destacada":  false
    },
    {
        "id":  "1197-bahia-con-playa",
        "titulo":  "Bahia con playa",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1197-bahia-con-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1198-playa-al-sur-de-pto-montt",
        "titulo":  "Playa al sur de Pto Montt",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1198-playa-al-sur-de-pto-montt.jpg",
        "destacada":  false
    },
    {
        "id":  "1199-playa-al-sur-de-pto-montt",
        "titulo":  "Playa al sur de Pto Montt",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1199-playa-al-sur-de-pto-montt.jpg",
        "destacada":  false
    },
    {
        "id":  "1200-castillo-en-el-mar",
        "titulo":  "Castillo en el mar",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1200-castillo-en-el-mar.jpg",
        "destacada":  false
    },
    {
        "id":  "1201-bahia-mar-dia-sol",
        "titulo":  "Bahia mar dia sol",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1201-bahia-mar-dia-sol.jpg",
        "destacada":  false
    },
    {
        "id":  "1202-bahia-mar-dia-nublado",
        "titulo":  "Bahia mar dia nublado",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1202-bahia-mar-dia-nublado.jpg",
        "destacada":  false
    },
    {
        "id":  "1203-mar-puesta-de-sol",
        "titulo":  "Mar puesta de sol",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1203-mar-puesta-de-sol.jpg",
        "destacada":  false
    },
    {
        "id":  "1204-rocas-de-orilla-marcando-nuveles-del-lago",
        "titulo":  "Rocas de orilla marcando nuveles del lago",
        "anio":  2026,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1204-rocas-de-orilla-marcando-nuveles-del-lago.jpg",
        "destacada":  true
    },
    {
        "id":  "1205-camino-al-puente-post-terremoto",
        "titulo":  "Camino al puente post terremoto",
        "anio":  1985,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1205-camino-al-puente-post-terremoto.jpg",
        "destacada":  false
    },
    {
        "id":  "1205-rocas-en-el-rio",
        "titulo":  "Rocas en el rio",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1205-rocas-en-el-rio.jpg",
        "destacada":  false
    },
    {
        "id":  "1206-rio-correntoso",
        "titulo":  "Rio correntoso",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1206-rio-correntoso.jpg",
        "destacada":  false
    },
    {
        "id":  "1208-hofbauer-artista-en-londres-uk",
        "titulo":  "Hofbauer, artista en Londres UK",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1208-hofbauer-artista-en-londres-uk.jpg",
        "destacada":  false
    },
    {
        "id":  "1209-rio-con-rocas",
        "titulo":  "Rio con rocas",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1209-rio-con-rocas.jpg",
        "destacada":  false
    },
    {
        "id":  "1210-mi-taller-de-pintura-en-escuela-de-arte-londres-bosquejo-a-color",
        "titulo":  "Mi taller de pintura en escuela de arte, Londres bosquejo a color",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Bosquejo",
        "medidas":  "",
        "imagen":  "assets/obras/1210-mi-taller-de-pintura-en-escuela-de-arte-londres-bosquejo-a-color.jpg",
        "destacada":  false
    },
    {
        "id":  "1211-al-aterdecer",
        "titulo":  "Al aterdecer",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1211-al-aterdecer.jpg",
        "destacada":  false
    },
    {
        "id":  "1212-cata-y-peter-en-temuco",
        "titulo":  "Cata y Peter en Temuco",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1212-cata-y-peter-en-temuco.jpg",
        "destacada":  false
    },
    {
        "id":  "1213-autoretrato",
        "titulo":  "Autoretrato",
        "anio":  2026,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1213-autoretrato.jpg",
        "destacada":  true
    },
    {
        "id":  "1214-vista-al-volcan-villarica",
        "titulo":  "Vista al volcan Villarica",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1214-vista-al-volcan-villarica.jpg",
        "destacada":  false
    },
    {
        "id":  "1215-mujer-desnuda-en-la-cabana",
        "titulo":  "Mujer desnuda en la cabana",
        "anio":  null,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1215-mujer-desnuda-en-la-cabana.jpg",
        "destacada":  false
    },
    {
        "id":  "1216-la-escala",
        "titulo":  "La Escala",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1216-la-escala.jpg",
        "destacada":  false
    },
    {
        "id":  "1217-mi-amiga-anne-lise-de-nyon-suiza",
        "titulo":  "Mi amiga Anne Lise de Nyon Suiza",
        "anio":  1971,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1217-mi-amiga-anne-lise-de-nyon-suiza.jpg",
        "destacada":  false
    },
    {
        "id":  "1218-mujer-entre-las-rocas",
        "titulo":  "Mujer entre las rocas",
        "anio":  2026,
        "categoria":  "figura",
        "tematica":  "Figura",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1218-mujer-entre-las-rocas.jpg",
        "destacada":  true
    },
    {
        "id":  "1219-remanso-en-el-trafanpulli",
        "titulo":  "Remanso en el Trafanpulli",
        "anio":  2026,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1219-remanso-en-el-trafanpulli.jpg",
        "destacada":  true
    },
    {
        "id":  "1220-bote-en-la-boya",
        "titulo":  "Bote en la boya",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1220-bote-en-la-boya.jpg",
        "destacada":  false
    },
    {
        "id":  "1221-mar-patagonico",
        "titulo":  "Mar patagonico",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1221-mar-patagonico.jpg",
        "destacada":  false
    },
    {
        "id":  "1222-rocas-en-la-playa",
        "titulo":  "Rocas en la playa",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1222-rocas-en-la-playa.jpg",
        "destacada":  false
    },
    {
        "id":  "1223-bote-con-boero",
        "titulo":  "Bote con boero",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1223-bote-con-boero.jpg",
        "destacada":  false
    },
    {
        "id":  "1224-bote-en-el-lago",
        "titulo":  "Bote en el lago",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1224-bote-en-el-lago.jpg",
        "destacada":  false
    },
    {
        "id":  "1225-bote-en-el-lago",
        "titulo":  "Bote en el lago",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1225-bote-en-el-lago.jpg",
        "destacada":  false
    },
    {
        "id":  "1226-arboles-en-la-nieve",
        "titulo":  "Arboles en la nieve",
        "anio":  null,
        "categoria":  "paisajes",
        "tematica":  "Paisaje",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1226-arboles-en-la-nieve.jpg",
        "destacada":  false
    },
    {
        "id":  "1227-tres-botes-en-el-mar",
        "titulo":  "Tres botes en el mar",
        "anio":  null,
        "categoria":  "marinas",
        "tematica":  "Marina",
        "tecnica":  "Óleo",
        "medidas":  "",
        "imagen":  "assets/obras/1227-tres-botes-en-el-mar.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-2",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-2.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-3",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-3.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-4",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-4.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-5",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-5.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-6",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-6.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-7",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-7.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-8",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-8.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-9",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-9.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-10",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-10.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-11",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-11.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-12",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-12.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-13",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-13.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-14",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-14.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-15",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-15.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-16",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-16.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-17",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-17.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-18",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-18.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-19",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-19.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-20",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-20.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-21",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-21.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-22",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-22.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-23",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-23.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-24",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-24.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-25",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-25.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-26",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-26.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-27",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-27.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-28",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-28.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-29",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-29.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-30",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-30.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-31",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-31.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-32",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-32.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-33",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-33.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-34",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-34.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-35",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-35.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-36",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-36.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-37",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-37.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-38",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-38.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-39",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-39.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-40",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-40.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-41",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-41.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-42",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-42.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-43",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-43.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-44",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-44.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-45",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-45.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-46",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-46.jpg",
        "destacada":  false
    },
    {
        "id":  "dsc-47",
        "titulo":  "DSC",
        "anio":  null,
        "categoria":  "dibujos",
        "tematica":  "Desnudo",
        "tecnica":  "Lápiz",
        "medidas":  "",
        "imagen":  "assets/obras/dsc-47.jpg",
        "destacada":  false
    }
];
